### ISSUE TITLE
UK to GB transition testing plan in staging

### ISSUE THREAD

**Issue by aurangzaib048** [brave/news-aggregator#340]
```[tasklist]
### Tasks
- [ ] Set `en-US` locale from your system settings
- [ ] Launch Brave using `--brave-today-host=brave-today-cdn.bravesoftware.com`
- [ ] Enable Brave News
- [ ] Check the default following sources feed (Are the feed coming from US)
- [ ] Scroll Down and see feed is loading proper and feed images are loading proper
- [ ] Add some custom sources
```
### Expected results:

- [ ] Check the cover images of the publishers (Most of the publishers cover image should be visible). Ignore the rest of the publisher's cover image
- [ ] This should only display US-based feeds, in English

Repeat this process for `en-GB`, `en_CA`, `es_ES`, `es-MX`, `ja-JP` and `pt_BR`

**Comment by aurangzaib048** [comment]
cc: @mattmcalister

**Comment by mattmcalister** [comment]
`en_GB` sources can be identified by going to the Settings/Discovery and looking at the Popular Sources list. You will find the following, in order: 

1. BBC
2. The Guardian
3. Daily Mail
4. The Independent
5. ...etc

Publishers for each locale can be found in the sources.[lang_REGION].csv files here: https://github.com/brave/news-aggregator/tree/master/sources, such as https://github.com/brave/news-aggregator/blob/master/sources/sources.en_GB.csv

**Comment by stephendonner** [comment]
## Verified `PASSED` for me on desktop, using 

Brave | 1.48.152 Chromium: 109.0.5414.119 (Official Build) beta (x86_64)
-- | --
Revision | 772095164c7d5d4e73160f858efed3b5e87eca83-refs/branch-heads/5414@{#1458}
OS | macOS Version 11.7.3 (Build 20G1116)

Tested using the testplan at https://github.com/brave/news-aggregator/issues/340#issue-1568667755, for all of the following locales/regions (I tested with native languages for all):

*en-GB
* en_CA
* es_ES
* es-MX
* ja-JP
* pt_BR

**Comment by Uni-verse** [comment]
In progress on Samsung Galaxy S21 5G using version:

```
Brave	1.48.155 Chromium: 110.0.5481.77 (Official Build) (64-bit) 
Revision	65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}
OS	Android 13; Build/TP1A.220624.014
```

**Comment by stephendonner** [comment]
@aurangzaib048 neither @Uni-verse nor I have access to close this issue out properly; mind taking care of it?  Thanks!

**Comment by aurangzaib048** [comment]
Transition Completed, Thanks to @stephendonner and @Uni-verse to test it.
