### ISSUE TITLE
Optimizations phase II -- test plan

### ISSUE THREAD

**Issue by aurangzaib048** [brave/news-aggregator#387]
### Tasks
- [ ] Set `en-US` locale from your system settings
- [ ] Launch Brave using `--brave-today-host=brave-today-cdn.bravesoftware.com`
- [ ] Enable Brave News
- [ ] Check the default following sources feed (Are the feed coming from US)
- [ ] Scroll Down and see feed is loading proper and feed images are loading proper
- [ ] Add some custom sources

### Expected results:

- [ ] Check if feed is correct and being updated.
- [ ] This should only display US-based feeds, in English

Repeat this process for `en-GB`, `en_CA`, `es_ES`, `es-MX`, `ja-JP` and `pt_BR`

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21 5G` using version:

```
Brave	1.51.60 Chromium: 112.0.5615.29 (Official Build) canary (64-bit) 
Revision	8a59304c62e066962363d2fd8edd8e7b459c42bd-refs/branch-heads/5615@{#497}
OS	Android 13; Build/TP1A.220624.014
```

Using Test Plan in https://github.com/brave/news-aggregator/issues/387#issue-1617573835

- Confirmed feed is loading properly and feed images are loading properly for `en-US`, `en-GB`, `en_CA`, `es_ES`, `es-MX`, `ja-JP` and `pt_BR`
- Confirmed adding custom sources is working

en-US | en-GB | en_CA | es_ES | es-MX | ja-JP | pt_BR
-|-|-|-|-|-|-
![screenshot-1679937682535](https://user-images.githubusercontent.com/17885425/228041470-230026dc-daa3-4b5f-8da5-70ed2d63c7dc.png) | ![screenshot-1679940199842](https://user-images.githubusercontent.com/17885425/228041532-1f477673-a9df-438a-8e8f-6c738a3f9d6d.png) | ![screenshot-1679941985478](https://user-images.githubusercontent.com/17885425/228041593-0ae4ba25-cec0-478a-ba74-669a6c107c1d.png) | ![screenshot-1679942789992](https://user-images.githubusercontent.com/17885425/228041699-76b8a8a5-04a2-4cde-8707-a9b76684a00e.png) | ![screenshot-1679943359071](https://user-images.githubusercontent.com/17885425/228041779-452d7cc6-7b72-4fff-ba5b-7d786054a731.png) | ![screenshot-1679944270086](https://user-images.githubusercontent.com/17885425/228043084-e4db34e0-44b2-4d98-b904-160b582e4908.png) | ![screenshot-1679944718702](https://user-images.githubusercontent.com/17885425/228044510-db0b735c-4643-462d-91fb-f746b3dc7ece.png)

**Comment by stephendonner** [comment]
Sorry for the delay on this @aurangzaib048 - I'll try to take a look this week, in-between a few other tasks.  Got slammed with Brave VPN.

In the future, I think it would be team-preferred to use the "Requesting QA resources" link under https://github.com/brave/qa-resources/issues/new/choose, that way @kjozwiak and/or @LaurenWags can help us all better-triage our time accordingly on it.  Thanks!

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.51.79 Chromium: 112.0.5615.49 (Official Build) beta (x86_64)
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | macOS Version 11.7.5 (Build 20G1225)

en-GB, en_CA, es_ES, es-MX, ja-JP and pt_BR




--brave-today-host=brave-today-cdn.bravesoftware.com

**Comment by aurangzaib048** [comment]
Completed!
