### ISSUE TITLE
Improve pixellated/low quality images for several publishers/locales

### ISSUE THREAD

**Issue by LorenzoMinto** [brave/news-aggregator#679]
```[tasklist]
### Tasks
- [ ] Improve images parsing for several publishers/locales
- [ ] https://github.com/brave/news-aggregator/issues/683
```

List of publisher affected, some inconsistently (not final)

**UK**

- [ ] Sky News
- [ ] Indiewire
- [ ] Daily Mail
- [ ] BBC Good Food
- [ ] Autocar
- [ ] Gamespot
- [ ] This Is Money
- [ ] Radio Times

**US**

- [ ] The New York Times

**Comment by SWB90** [comment]
![Screenshot 2023-12-05 at 13 44 29](https://github.com/brave/news-aggregator/assets/43574136/89ae22b6-35fe-4c80-ac9c-347302a08973)
[Radio Times (UK)](https://www.radiotimes.com/tv/entertainment/reality-tv/im-a-celebrity-2023-recap/)

**Comment by LorenzoMinto** [comment]
@aurangzaib048 were all the above publishers resolved?

**Comment by aurangzaib048** [comment]
Yes, the above mentioned all the publisher's images are in good quality now.

**Comment by LorenzoMinto** [comment]
Thanks Rana 💯
